spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(w/42Emgvde0KuhS1zqC/UJ7QXemH8rlTf+8ADw4X+xC76uXhHaiHWA==)
    username: ENC(Ws5JbqTT5uKx7MHcKV9JmA==)
    password: ENC(7JqtAw31LzbkYDi+aQkdBA==)

  jasypt:
    encryptor:
      bean: jasyptStringEncryptor
      password: ${ENCRYPT_KEY}

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

  config:
    import: "classpath:application_secret.yml"  # application_secret.yml ?? ????

logging:
  level:
    root: INFO
